export JAVA_HOME=/etc/alternatives/jre_17
export SPARK_HOME=/opt/spark/spark-3.5.1-bin-hadoop3
export PATH="$JAVA_HOME/bin:$SPARK_HOME/bin:$PATH"

DP_LF_564871=dummy spark-submit --master yarn --conf spark.driver.extraClassPath=/opt/tpcds/jars/datapelago-gv-bundle-spark3.5_2.12-amzn_2023_x86_64-1.4.0-SNAPSHOT-s3-7apr.jar:/opt/tpcds/jars/jackson-databind-2.15.2.jar:/opt/tpcds/jars/jackson-annotations-2.15.2.jar:/usr/lib/hadoop/hadoop-common.jar:/usr/lib/hadoop/hadoop-hdfs.jar:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/aws-java-sdk-bundle-1.12.705.jar:/usr/share/aws/aws-java-sdk-v2/aws-sdk-java-bundle-2.23.18.jar:/usr/lib/hadoop/lib/* --conf spark.executor.extraClassPath=/opt/tpcds/jars/datapelago-gv-bundle-spark3.5_2.12-amzn_2023_x86_64-1.4.0-SNAPSHOT-s3-7apr.jar:/opt/tpcds/jars/jackson-databind-2.15.2.jar:/opt/tpcds/jars/jackson-annotations-2.15.2.jar:/usr/lib/hadoop/hadoop-common.jar:/usr/lib/hadoop/hadoop-hdfs.jar:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/aws-java-sdk-bundle-1.12.705.jar:/usr/share/aws/aws-java-sdk-v2/aws-sdk-java-bundle-2.23.18.jar:/usr/lib/hadoop/lib/* --conf spark.driver.log.level=ERROR  --conf spark.executor.log.level=WARN --conf spark.plugins=org.apache.gluten.GlutenPlugin --conf spark.memory.offHeap.enabled=true --conf spark.memory.offHeap.size=4g --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager --conf spark.gluten.dp.enabled=true --conf spark.gluten.dp.subid=test --conf spark.driver.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" --conf spark.executor.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true"  --conf spark.executorEnv.DP_LF_564871=dummy tpcdsdplggdriver.py

{'q23a': 8.66490912437439, 'q23b': 6.032731294631958, 'q14a': 10.643115282058716, 'q14b': 7.739255428314209}
{'q23a': 9.009395360946655, 'q23b': 6.43305230140686, 'q14a': 10.47572946548462, 'q14b': 7.7196946144104}
{'q23a': 11.8117196559906, 'q23b': 7.568789958953857, 'q14a': 8.757649898529053, 'q14b': 6.490747451782227}

pyspark --master yarn --conf spark.driver.extraClassPath=/opt/tpcds/jars/datapelago-gv-bundle-spark3.5_2.12-amzn_2023_x86_64-1.4.0-SNAPSHOT-s3-7apr.jar:/opt/tpcds/jars/jackson-databind-2.15.2.jar:/opt/tpcds/jars/jackson-annotations-2.15.2.jar:/usr/lib/hadoop/hadoop-common.jar:/usr/lib/hadoop/hadoop-hdfs.jar:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/aws-java-sdk-bundle-1.12.705.jar:/usr/share/aws/aws-java-sdk-v2/aws-sdk-java-bundle-2.23.18.jar:/usr/lib/hadoop/lib/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/* --conf spark.executor.extraClassPath=/opt/tpcds/jars/datapelago-gv-bundle-spark3.5_2.12-amzn_2023_x86_64-1.4.0-SNAPSHOT-s3-7apr.jar:/opt/tpcds/jars/jackson-databind-2.15.2.jar:/opt/tpcds/jars/jackson-annotations-2.15.2.jar:/usr/lib/hadoop/hadoop-common.jar:/usr/lib/hadoop/hadoop-hdfs.jar:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/aws-java-sdk-bundle-1.12.705.jar:/usr/share/aws/aws-java-sdk-v2/aws-sdk-java-bundle-2.23.18.jar:/usr/lib/hadoop/lib/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/* --conf spark.driver.log.level=ERROR  --conf spark.executor.log.level=WARN --conf spark.plugins=org.apache.gluten.GlutenPlugin --conf spark.memory.offHeap.enabled=true --conf spark.memory.offHeap.size=4g --conf spark.shuffle.manager=org.apache.spark.shuffle.sort.ColumnarShuffleManager --conf spark.gluten.dp.enabled=true --conf spark.gluten.dp.subid=test --conf spark.driver.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true" --conf spark.executor.extraJavaOptions="-Dio.netty.tryReflectionSetAccessible=true"  --conf spark.executorEnv.DP_LF_564871=dummy --conf spark.hadoop.hive.metastore.client.factory.class=com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory --conf spark.sql.warehouse.dir=s3://dovertestbucket/tpcds_1TB_dataset/raw/tpc-ds/source_files_001TB_parquet/warehouse/
